# Generated by Django 4.2.7 on 2025-10-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='订单号')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='成交价格')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='定金')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('confirmed', '卖家确认'), ('shipped', '已发货'), ('delivered', '已送达'), ('completed', '已完成'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=15, verbose_name='订单状态')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行转账'), ('cash', '现金')], max_length=10, verbose_name='支付方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('shipping_address', models.TextField(verbose_name='收货地址')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='物流单号')),
                ('shipping_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='物流公司')),
                ('buyer_notes', models.TextField(blank=True, null=True, verbose_name='买家备注')),
                ('seller_notes', models.TextField(blank=True, null=True, verbose_name='卖家备注')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='取消原因')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='车辆')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '交易订单',
                'verbose_name_plural': '交易订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15, verbose_name='状态')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transactions.transaction')),
            ],
            options={
                'verbose_name': '交易历史',
                'verbose_name_plural': '交易历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='评分')),
                ('comment', models.TextField(verbose_name='评价内容')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名评价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
                ('reviewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL, verbose_name='被评价人')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评价人')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction', verbose_name='交易')),
            ],
            options={
                'verbose_name': '交易评价',
                'verbose_name_plural': '交易评价',
                'unique_together': {('transaction', 'reviewer')},
            },
        ),
    ]
