# Generated by Django 4.2.7 on 2025-10-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='品牌名称')),
                ('brand_type', models.CharField(choices=[('domestic', '国产品牌'), ('imported', '进口品牌')], default='domestic', max_length=10, verbose_name='品牌类型')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand_logos/', verbose_name='品牌Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='品牌描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '汽车品牌',
                'verbose_name_plural': '汽车品牌',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='车型')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='里程(公里)')),
                ('color', models.CharField(max_length=50, verbose_name='颜色')),
                ('transmission', models.CharField(choices=[('manual', '手动'), ('automatic', '自动'), ('semi_auto', '半自动')], max_length=10, verbose_name='变速箱')),
                ('fuel_type', models.CharField(choices=[('gasoline', '汽油'), ('diesel', '柴油'), ('electric', '电动'), ('hybrid', '混合动力')], max_length=10, verbose_name='燃料类型')),
                ('engine_capacity', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='排量(L)')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='原价')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='当前价格')),
                ('ai_suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='AI建议价格')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '审核通过'), ('rejected', '审核不通过'), ('sold', '已售出'), ('maintenance', '维修中')], default='pending', max_length=15, verbose_name='状态')),
                ('main_image', models.ImageField(upload_to='car_images/', verbose_name='主图')),
                ('description', models.TextField(verbose_name='车辆描述')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('category', models.CharField(choices=[('sedan', '轿车'), ('suv', 'SUV'), ('mpv', 'MPV'), ('coupe', '跑车'), ('hatchback', '掀背车'), ('wagon', '旅行车'), ('pickup', '皮卡')], max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '汽车类型',
                'verbose_name_plural': '汽车类型',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/', verbose_name='图片')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
            options={
                'verbose_name': '车辆图片',
                'verbose_name_plural': '车辆图片',
            },
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100, verbose_name='特性名称')),
                ('feature_value', models.CharField(max_length=200, verbose_name='特性值')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car')),
            ],
            options={
                'verbose_name': '车辆特性',
                'verbose_name_plural': '车辆特性',
            },
        ),
    ]
