# Generated by Django 4.2.7 on 2025-10-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('car_features', '车辆特征'), ('price_history', '价格历史'), ('user_behavior', '用户行为'), ('market_data', '市场数据')], max_length=50, verbose_name='数据类型')),
                ('data_content', models.JSONField(verbose_name='数据内容')),
                ('data_source', models.CharField(max_length=100, verbose_name='数据来源')),
                ('is_processed', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI训练数据',
                'verbose_name_plural': 'AI训练数据',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_range', models.CharField(choices=[('0-5', '0-5万'), ('5-10', '5-10万'), ('10-20', '10-20万'), ('20-50', '20-50万'), ('50+', '50万以上')], default='10-20', max_length=10, verbose_name='预算范围')),
                ('min_year', models.IntegerField(default=2015, verbose_name='最小年份')),
                ('max_mileage', models.DecimalField(decimal_places=2, default=100000, max_digits=10, verbose_name='最大里程')),
                ('preferred_fuel_types', models.JSONField(default=list, verbose_name='偏好燃料类型')),
                ('preferred_transmissions', models.JSONField(default=list, verbose_name='偏好变速箱')),
                ('search_history', models.JSONField(default=list, verbose_name='搜索历史')),
                ('click_history', models.JSONField(default=list, verbose_name='点击历史')),
                ('favorite_categories', models.JSONField(default=list, verbose_name='收藏类别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('preferred_brands', models.ManyToManyField(blank=True, to='cars.brand', verbose_name='偏好品牌')),
                ('preferred_types', models.ManyToManyField(blank=True, to='cars.cartype', verbose_name='偏好类型')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
            },
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='预测价格')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='置信度')),
                ('market_trend', models.CharField(choices=[('rising', '上涨'), ('stable', '稳定'), ('declining', '下跌')], max_length=20, verbose_name='市场趋势')),
                ('influencing_factors', models.JSONField(default=list, verbose_name='影响因素')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预测时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_prediction', to='cars.car')),
            ],
            options={
                'verbose_name': '价格预测',
                'verbose_name_plural': '价格预测',
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_reason', models.TextField(verbose_name='推荐理由')),
                ('match_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='匹配度')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='是否查看')),
                ('is_clicked', models.BooleanField(default=False, verbose_name='是否点击')),
                ('user_rating', models.IntegerField(blank=True, null=True, verbose_name='用户评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='推荐时间')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='推荐车辆')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI推荐',
                'verbose_name_plural': 'AI推荐',
                'ordering': ['-match_score'],
            },
        ),
    ]
